### PR TITLE
WIKI-1280 : Attached image with whitespace is not working

### PR DESCRIPTION
**Pull request by aboughzela**
whitespace should replaced by "_" ( as jcr implimentation : https://github.com/exodev/wiki/blob/develop/wiki-service/src/main/java/org/exoplatform/wiki/mow/core/api/wiki/PageImpl.java#L282  )

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
This works, but only for new images. I still have the issue with images inserted before this fix.
Why not simply removing the id resolving in https://github.com/exodev/wiki/blob/develop/wiki-service/src/main/java/org/exoplatform/wiki/rendering/impl/DefaultWikiModel.java#L129 ?

**Comment by aboughzela** [comment]
yes, it's an other solution ( removing the id resolving from DefaultWikiModel.java)
change this logic , make impossible for any one to switch to jcr implementation
(jcr node name cannot contain  whitespace)
WDYT ?

**Comment by thomasdelhomenie** [comment]
JCR implementation is not supported anymore in 4.4.

**Comment by aboughzela** [comment]
it's OK PR updated

**Pull request closed without merging**
